version: '3.8'

services:
  app:
    image: profilo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./public:/app/public
    # environment:
    #   NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    #   CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    #   DATABASE_URL: ${DATABASE_URL}
    #   STRIPE_API_KEY: ${STRIPE_API_KEY}
    #   STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    #   NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: neondb
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
